version: '3'

services:
  backend:
    image: node:18
    container_name: backend
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run start

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
